extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
env:
  browser: true
  es6: true
  node: true
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
settings:
  react:
    version: detect
rules:
  'react/prop-types': [0]
  'react/display-name': [0]
  no-useless-escape: [0]
  prefer-const: ['error']
  no-unused-vars: [0]
